server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.68.244:3306/support_shop?useUnicode=true&characterEncoding=UTF-8
    username: hdys_live
    password: wo982694307
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 5
    #最大连接等待超时时间
    maxWait: 60000
    servlet:
      multipart:
        enabled: true
        max-file-size: 2MB
        max-request-size: 20MB
  redis:
    #host: 10.20.20.136
    host: 127.0.0.1
    # 端口
    port: 6379
    # 超时时间
    timeout: 5000
    jedis:
      pool:
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中最小空闲连接
        min-idle: 2

  # MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage:  com.carry.www.*
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# PageHelper分页插件
pagehelper:
  #helperDialect: oracle
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

  # 日志配置
logging:
  level:
    com.fencer: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#其他配置公共属性